### ISSUE TITLE
Cannot compile on Mac

### ISSUE THREAD

**Issue by kevinresol** [openfl/lime#420]
It gives the same compile error when I compile for neko, mac or ios, with or without -Dv2
```
Called from openfl/_v2/utils/ByteArray.hx line 757
Called from openfl/_v2/Lib.hx line 272
Called from openfl/_v2/Lib.hx line 415
Called from openfl/_v2/Lib.hx line 207
Called from /usr/lib/haxe/std/neko/Lib.hx line 30
Uncaught exception - load.c(237) : Failed to load library : lime.ndll (dlopen(lime.ndll, 1): image not found)
```

haxelib:
```
haxelib_client: [3.2.0-rc.3]
hxcpp: 3.1.39 3.1.68 [3.2.81]
lime-samples: [2.3.0]
lime-tools: [1.5.7]
lime: 1.0.1 2.0.0-alpha 2.0.0-alpha.5 2.1.3 [2.3.3]
openfl-samples: 1.3.0 2.1.0 [2.2.2]
openfl: 2.0.1 2.1.0-beta 2.1.3 2.2.8 [3.0.3]
swf: 1.5.2 1.5.3 1.6.5 1.7.3 1.7.7 [1.8.6]
```

**Comment by jgranick** [comment]
I believe this has been resolved, but let me know if you still have trouble with the latest releases :smile:

**Comment by kevinresol** [comment]
Seems another error emerged...
```
 lime test ios
Called from lime/utils/ByteArray.hx line 110
Called from lime/system/System.hx line 304
Called from lime/system/System.hx line 419
Uncaught exception - Segmentation fault
```

```
haxelib_client: [3.2.0-rc.3]
lime: 1.0.1 2.0.0-alpha 2.0.0-alpha.5 2.1.3 2.3.3 [2.4.1]
openfl: 2.0.1 2.1.0-beta 2.1.3 2.2.8 3.0.3 [3.0.6]
hxcpp: 3.1.39 3.1.68 3.2.81 [3.2.94]
swf: 1.5.2 1.5.3 1.6.5 1.7.3 1.7.7 1.8.6 [1.8.7]
```

**Comment by jgranick** [comment]
What version of Haxe do you have? How did you install Haxe? Did Lime finish downloading and installing? (some RC versions of Haxe 3.2 did not install Lime fully)

**Comment by kevinresol** [comment]
I was using the 3.2 release version, I downloaded the Mac Installer from haxe.org. I have lime installed completely.

Looking at line 110 of ByteArray.hx, I think there are some problem regarding to the library loading. How can I debug from there?

Btw, I just updated to dev version of haxe + lime 2.4.4 + openfl 3.1.0 + swf 1.8.8 + hxcpp 3.2.102 but still no luck. The same error happens.
